name: config_annotations
description: Anotaciones utilizadas para generar un archivo de configuracion desde json.
version: 1.0.0
author: Diego Cardenas <diegoefraincardenas@gmail.com>
homepage: git@github.com:rbellota30/Config_Annotations.git

environment:
  sdk: ">=2.12.0 <3.0.0"
